language: python
python:
- '3.6'
env:
- TOXENV=py36
install: pip install -U tox
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  user: __token__
  password:
    secure: G4kdGH0KLhNXcAlaJQAc48EQ9NybV/2rpfAXfKB5Fagn/DtE1J+3QzGq9XbLYF3QQO57GV/8G/w3pYOPM0nyMV00pQnigfOsyu32w7/K5QC2RMig0wLwd4TyQfG2hcC9JvznYjWbTsHWsoRHC3VgQS7SmXEhdzK6KsA5dfrowXgoq0H5KOo1uZJZp67yJFr7DimbpweOB8PsGurUYtNFkWmqBh+6j9iddXO7EVlz9TwRpVBYW3dqmIuBU8inMrJoxbK3NrTOaLDhIx7oQsovwkhFlAXNqy0nMsJgZ6b/mfp2N3We0e/Vo5Kt3WNd27P6YYPqxqK6ckKqyxb61nq8oOOkdTvyX/Yyxq6ayGLT92s80Wgggh7kmmgg0QIm4aYsHUGF9K9YjxV2ywosUlwuN//tLxdqjwA11qhy/9ATRvyi8HsGpt2s0TLhIJoWmuqd2UoJx6sygI3Vuj0zYguvFf0eMFQoMF7JA59fxXwwj2VnGGWH9Tiar7tSJWHJCC+LSfXrDnp/6S8JuzVm1Kk0IRzERkBIUTTA7pf7EZQa1p+Z/Wd2VrEGDDKqhkFszJeNpyORcbtm5/SH9OtcWEk38PNcexZ6o/dkQwZEXkVwZmQBsthD859HpgL5hni0utEsPGH7G7etEG1HELBdNMGNAGLkE0XnT8l3nF+CDvRoxxo=
  on:
    tags: true
